services:
  database:
    container_name: database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: segmentation_fault
      MYSQL_USER: segmentation_fault
      MYSQL_PASSWORD: aBo0pxbV@YQ5FARIEIbS
    image: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - database
    env_file:
      - ./backend/.env
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./frontend:/app
